$schemaver: '2.0'
repo_url: https://github.com/byu-oit/byu-wabs-oauth
software:
  - name: byu-wabs-oauth
    type: Library
    aliases:
    short_description: Convenience library to handle oauth requests specific to BYU's
      well-known configuration data
    assignment_group: gro:AD-Academic Information Management
    notes:
    maintained_by:
      - mhailstone
      - Gi60s
    developed_by_byu: true
    ddd:
      business_domain:
      ubiquitous_language_url:
      context_map_url:
    links:
      system_documentation_url: https://github.com/byu-oit/byu-wabs-oauth
      swagger_urls:
    microservice: false
    technologies_used:
      - JavaScript
      - TypeScript
      - NodeJS
    stages:
      production:
        urls:
          product_page:
          physical_url:
          virtual_url:
        hosting_location: BYU
        aws_account:
        relationships:
          depends_on:
            db_read_write:
            db_read_only:
            software:
          supports:
            software:
            service:
          reverse_proxy:
          runs_on:
            server_cluster:
            virtual_server:
            rack_server:
            blade_server:
    tags:
      data-sensitivity: confidential
      app: byu-wabs-oauth
      team: gro:AD-Academic Information Management
